# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Sam Turnbull
tagline:          'Blog'
description:      ''
url:              http://samturnbull.com
baseurl:          /

author:
  name:           'Sam Turnbull'
  url:            https://twitter.com/sam_dunk

gems:             [jekyll-paginate]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samturnbull
